/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OptimizerIndexRouteImport } from './routes/optimizer/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BattleIndexRouteImport } from './routes/battle/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PromptIdRouteImport } from './routes/prompt/$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as CreatorUsernameRouteImport } from './routes/creator/$username'
import { Route as BattleLeaderboardRouteImport } from './routes/battle/leaderboard'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DashboardCreatorIndexRouteImport } from './routes/dashboard/creator/index'
import { Route as DashboardCollectionsIndexRouteImport } from './routes/dashboard/collections/index'
import { Route as DashboardCreatorUploadRouteImport } from './routes/dashboard/creator/upload'
import { Route as DashboardCollectionsIdRouteImport } from './routes/dashboard/collections/$id'
import { Route as DashboardCreatorEditIdRouteImport } from './routes/dashboard/creator/edit/$id'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerIndexRoute = OptimizerIndexRouteImport.update({
  id: '/optimizer/',
  path: '/optimizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIndexRoute = BattleIndexRouteImport.update({
  id: '/battle/',
  path: '/battle/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptIdRoute = PromptIdRouteImport.update({
  id: '/prompt/$id',
  path: '/prompt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorUsernameRoute = CreatorUsernameRouteImport.update({
  id: '/creator/$username',
  path: '/creator/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleLeaderboardRoute = BattleLeaderboardRouteImport.update({
  id: '/battle/leaderboard',
  path: '/battle/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreatorIndexRoute = DashboardCreatorIndexRouteImport.update({
  id: '/dashboard/creator/',
  path: '/dashboard/creator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCollectionsIndexRoute =
  DashboardCollectionsIndexRouteImport.update({
    id: '/dashboard/collections/',
    path: '/dashboard/collections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCreatorUploadRoute = DashboardCreatorUploadRouteImport.update({
  id: '/dashboard/creator/upload',
  path: '/dashboard/creator/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCollectionsIdRoute = DashboardCollectionsIdRouteImport.update({
  id: '/dashboard/collections/$id',
  path: '/dashboard/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreatorEditIdRoute = DashboardCreatorEditIdRouteImport.update({
  id: '/dashboard/creator/edit/$id',
  path: '/dashboard/creator/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/battle/leaderboard': typeof BattleLeaderboardRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/prompt/$id': typeof PromptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/battle/': typeof BattleIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/lab/': typeof LabIndexRoute
  '/optimizer/': typeof OptimizerIndexRoute
  '/dashboard/collections/$id': typeof DashboardCollectionsIdRoute
  '/dashboard/creator/upload': typeof DashboardCreatorUploadRoute
  '/dashboard/collections/': typeof DashboardCollectionsIndexRoute
  '/dashboard/creator/': typeof DashboardCreatorIndexRoute
  '/dashboard/creator/edit/$id': typeof DashboardCreatorEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/battle/leaderboard': typeof BattleLeaderboardRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/prompt/$id': typeof PromptIdRoute
  '/admin': typeof AdminIndexRoute
  '/battle': typeof BattleIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/community': typeof CommunityIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/lab': typeof LabIndexRoute
  '/optimizer': typeof OptimizerIndexRoute
  '/dashboard/collections/$id': typeof DashboardCollectionsIdRoute
  '/dashboard/creator/upload': typeof DashboardCreatorUploadRoute
  '/dashboard/collections': typeof DashboardCollectionsIndexRoute
  '/dashboard/creator': typeof DashboardCreatorIndexRoute
  '/dashboard/creator/edit/$id': typeof DashboardCreatorEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/battle/leaderboard': typeof BattleLeaderboardRoute
  '/creator/$username': typeof CreatorUsernameRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/prompt/$id': typeof PromptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/battle/': typeof BattleIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/lab/': typeof LabIndexRoute
  '/optimizer/': typeof OptimizerIndexRoute
  '/dashboard/collections/$id': typeof DashboardCollectionsIdRoute
  '/dashboard/creator/upload': typeof DashboardCreatorUploadRoute
  '/dashboard/collections/': typeof DashboardCollectionsIndexRoute
  '/dashboard/creator/': typeof DashboardCreatorIndexRoute
  '/dashboard/creator/edit/$id': typeof DashboardCreatorEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/notifications'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/battle/leaderboard'
    | '/creator/$username'
    | '/dashboard/settings'
    | '/prompt/$id'
    | '/admin/'
    | '/battle/'
    | '/categories/'
    | '/community/'
    | '/dashboard/'
    | '/lab/'
    | '/optimizer/'
    | '/dashboard/collections/$id'
    | '/dashboard/creator/upload'
    | '/dashboard/collections/'
    | '/dashboard/creator/'
    | '/dashboard/creator/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/notifications'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/battle/leaderboard'
    | '/creator/$username'
    | '/dashboard/settings'
    | '/prompt/$id'
    | '/admin'
    | '/battle'
    | '/categories'
    | '/community'
    | '/dashboard'
    | '/lab'
    | '/optimizer'
    | '/dashboard/collections/$id'
    | '/dashboard/creator/upload'
    | '/dashboard/collections'
    | '/dashboard/creator'
    | '/dashboard/creator/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/notifications'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/battle/leaderboard'
    | '/creator/$username'
    | '/dashboard/settings'
    | '/prompt/$id'
    | '/admin/'
    | '/battle/'
    | '/categories/'
    | '/community/'
    | '/dashboard/'
    | '/lab/'
    | '/optimizer/'
    | '/dashboard/collections/$id'
    | '/dashboard/creator/upload'
    | '/dashboard/collections/'
    | '/dashboard/creator/'
    | '/dashboard/creator/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BattleLeaderboardRoute: typeof BattleLeaderboardRoute
  CreatorUsernameRoute: typeof CreatorUsernameRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  PromptIdRoute: typeof PromptIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BattleIndexRoute: typeof BattleIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  OptimizerIndexRoute: typeof OptimizerIndexRoute
  DashboardCollectionsIdRoute: typeof DashboardCollectionsIdRoute
  DashboardCreatorUploadRoute: typeof DashboardCreatorUploadRoute
  DashboardCollectionsIndexRoute: typeof DashboardCollectionsIndexRoute
  DashboardCreatorIndexRoute: typeof DashboardCreatorIndexRoute
  DashboardCreatorEditIdRoute: typeof DashboardCreatorEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer/': {
      id: '/optimizer/'
      path: '/optimizer'
      fullPath: '/optimizer/'
      preLoaderRoute: typeof OptimizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/': {
      id: '/battle/'
      path: '/battle'
      fullPath: '/battle/'
      preLoaderRoute: typeof BattleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$id': {
      id: '/prompt/$id'
      path: '/prompt/$id'
      fullPath: '/prompt/$id'
      preLoaderRoute: typeof PromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$username': {
      id: '/creator/$username'
      path: '/creator/$username'
      fullPath: '/creator/$username'
      preLoaderRoute: typeof CreatorUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/leaderboard': {
      id: '/battle/leaderboard'
      path: '/battle/leaderboard'
      fullPath: '/battle/leaderboard'
      preLoaderRoute: typeof BattleLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/': {
      id: '/dashboard/creator/'
      path: '/dashboard/creator'
      fullPath: '/dashboard/creator/'
      preLoaderRoute: typeof DashboardCreatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/collections/': {
      id: '/dashboard/collections/'
      path: '/dashboard/collections'
      fullPath: '/dashboard/collections/'
      preLoaderRoute: typeof DashboardCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/upload': {
      id: '/dashboard/creator/upload'
      path: '/dashboard/creator/upload'
      fullPath: '/dashboard/creator/upload'
      preLoaderRoute: typeof DashboardCreatorUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/collections/$id': {
      id: '/dashboard/collections/$id'
      path: '/dashboard/collections/$id'
      fullPath: '/dashboard/collections/$id'
      preLoaderRoute: typeof DashboardCollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/edit/$id': {
      id: '/dashboard/creator/edit/$id'
      path: '/dashboard/creator/edit/$id'
      fullPath: '/dashboard/creator/edit/$id'
      preLoaderRoute: typeof DashboardCreatorEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  NotificationsRoute: NotificationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BattleLeaderboardRoute: BattleLeaderboardRoute,
  CreatorUsernameRoute: CreatorUsernameRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  PromptIdRoute: PromptIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BattleIndexRoute: BattleIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LabIndexRoute: LabIndexRoute,
  OptimizerIndexRoute: OptimizerIndexRoute,
  DashboardCollectionsIdRoute: DashboardCollectionsIdRoute,
  DashboardCreatorUploadRoute: DashboardCreatorUploadRoute,
  DashboardCollectionsIndexRoute: DashboardCollectionsIndexRoute,
  DashboardCreatorIndexRoute: DashboardCreatorIndexRoute,
  DashboardCreatorEditIdRoute: DashboardCreatorEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
